# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'krbai.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1037, 542)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1041, 531))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(510, 340, 441, 141))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_Start = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Start.setGeometry(QtCore.QRect(60, 50, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.pushButton_Stop = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Stop.setGeometry(QtCore.QRect(240, 50, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_Stop.setFont(font)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 471, 351))
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 161, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 171, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 151, 61))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 190, 151, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(20, 240, 151, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.Voltage_label = QtWidgets.QLabel(self.groupBox_3)
        self.Voltage_label.setGeometry(QtCore.QRect(190, 40, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setItalic(False)
        font.setKerning(False)
        self.Voltage_label.setFont(font)
        self.Voltage_label.setAutoFillBackground(True)
        self.Voltage_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Voltage_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Voltage_label.setLineWidth(5)
        self.Voltage_label.setMidLineWidth(19)
        self.Voltage_label.setText("")
        self.Voltage_label.setTextFormat(QtCore.Qt.AutoText)
        self.Voltage_label.setScaledContents(False)
        self.Voltage_label.setObjectName("Voltage_label")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(190, 90, 271, 41))
        self.label_3.setAutoFillBackground(True)
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setLineWidth(5)
        self.label_3.setMidLineWidth(19)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(190, 190, 271, 41))
        self.label_4.setAutoFillBackground(True)
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setLineWidth(5)
        self.label_4.setMidLineWidth(19)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(190, 140, 271, 41))
        self.label_9.setAutoFillBackground(True)
        self.label_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_9.setLineWidth(5)
        self.label_9.setMidLineWidth(19)
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(190, 240, 271, 41))
        self.label_10.setAutoFillBackground(True)
        self.label_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_10.setLineWidth(5)
        self.label_10.setMidLineWidth(19)
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(20, 290, 67, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(13)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(190, 290, 271, 41))
        self.label_19.setAutoFillBackground(True)
        self.label_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_19.setLineWidth(5)
        self.label_19.setMidLineWidth(19)
        self.label_19.setScaledContents(False)
        self.label_19.setObjectName("label_19")
        self.Depth_label = QtWidgets.QLabel(self.groupBox_3)
        self.Depth_label.setGeometry(QtCore.QRect(190, 290, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setItalic(True)
        self.Depth_label.setFont(font)
        self.Depth_label.setAutoFillBackground(True)
        self.Depth_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Depth_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Depth_label.setLineWidth(5)
        self.Depth_label.setMidLineWidth(19)
        self.Depth_label.setText("")
        self.Depth_label.setScaledContents(False)
        self.Depth_label.setObjectName("Depth_label")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setGeometry(QtCore.QRect(500, 50, 471, 301))
        self.groupBox_6.setAutoFillBackground(True)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(20, 40, 151, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(15)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(20, 130, 131, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(15)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(20, 210, 151, 61))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(15)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(170, 40, 271, 41))
        self.label_24.setAutoFillBackground(True)
        self.label_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_24.setLineWidth(5)
        self.label_24.setMidLineWidth(19)
        self.label_24.setScaledContents(False)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        self.label_25.setGeometry(QtCore.QRect(170, 130, 271, 41))
        self.label_25.setAutoFillBackground(True)
        self.label_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_25.setLineWidth(5)
        self.label_25.setMidLineWidth(19)
        self.label_25.setScaledContents(False)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_6)
        self.label_26.setGeometry(QtCore.QRect(170, 220, 271, 41))
        self.label_26.setAutoFillBackground(True)
        self.label_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_26.setLineWidth(5)
        self.label_26.setMidLineWidth(19)
        self.label_26.setScaledContents(False)
        self.label_26.setObjectName("label_26")
        self.InternalPresure_label = QtWidgets.QLabel(self.groupBox_3)
        self.InternalPresure_label.setGeometry(QtCore.QRect(190, 140, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setItalic(True)
        self.InternalPresure_label.setFont(font)
        self.InternalPresure_label.setAutoFillBackground(True)
        self.InternalPresure_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.InternalPresure_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.InternalPresure_label.setLineWidth(5)
        self.InternalPresure_label.setMidLineWidth(19)
        self.InternalPresure_label.setText("")
        self.InternalPresure_label.setScaledContents(False)
        self.InternalPresure_label.setObjectName("InternalPresure_label")
        self.Temperature_label = QtWidgets.QLabel(self.groupBox_3)
        self.Temperature_label.setGeometry(QtCore.QRect(190, 90, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setItalic(True)
        self.Temperature_label.setFont(font)
        self.Temperature_label.setAutoFillBackground(True)
        self.Temperature_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Temperature_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Temperature_label.setLineWidth(5)
        self.Temperature_label.setMidLineWidth(19)
        self.Temperature_label.setText("")
        self.Temperature_label.setScaledContents(False)
        self.Temperature_label.setObjectName("Temperature_label")
        self.Power_label = QtWidgets.QLabel(self.groupBox_3)
        self.Power_label.setGeometry(QtCore.QRect(190, 240, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setItalic(True)
        self.Power_label.setFont(font)
        self.Power_label.setAutoFillBackground(True)
        self.Power_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Power_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Power_label.setLineWidth(5)
        self.Power_label.setMidLineWidth(19)
        self.Power_label.setText("")
        self.Power_label.setScaledContents(False)
        self.Power_label.setObjectName("Power_label")
        self.Current_label = QtWidgets.QLabel(self.groupBox_3)
        self.Current_label.setGeometry(QtCore.QRect(190, 190, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setItalic(True)
        self.Current_label.setFont(font)
        self.Current_label.setAutoFillBackground(True)
        self.Current_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Current_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Current_label.setLineWidth(5)
        self.Current_label.setMidLineWidth(19)
        self.Current_label.setText("")
        self.Current_label.setScaledContents(False)
        self.Current_label.setObjectName("Current_label")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(510, 10, 471, 301))
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(20, 40, 151, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(20, 130, 131, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(20, 210, 151, 61))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.Roll_label = QtWidgets.QLabel(self.groupBox_5)
        self.Roll_label.setGeometry(QtCore.QRect(170, 40, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setItalic(True)
        self.Roll_label.setFont(font)
        self.Roll_label.setAutoFillBackground(True)
        self.Roll_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Roll_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Roll_label.setLineWidth(5)
        self.Roll_label.setMidLineWidth(19)
        self.Roll_label.setText("")
        self.Roll_label.setScaledContents(False)
        self.Roll_label.setObjectName("Roll_label")
        self.Pitch_label = QtWidgets.QLabel(self.groupBox_5)
        self.Pitch_label.setGeometry(QtCore.QRect(170, 130, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setItalic(True)
        self.Pitch_label.setFont(font)
        self.Pitch_label.setAutoFillBackground(True)
        self.Pitch_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Pitch_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Pitch_label.setLineWidth(5)
        self.Pitch_label.setMidLineWidth(19)
        self.Pitch_label.setText("")
        self.Pitch_label.setScaledContents(False)
        self.Pitch_label.setObjectName("Pitch_label")
        self.Yaw_label = QtWidgets.QLabel(self.groupBox_5)
        self.Yaw_label.setGeometry(QtCore.QRect(170, 220, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(14)
        font.setItalic(True)
        self.Yaw_label.setFont(font)
        self.Yaw_label.setAutoFillBackground(True)
        self.Yaw_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Yaw_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Yaw_label.setLineWidth(5)
        self.Yaw_label.setMidLineWidth(19)
        self.Yaw_label.setText("")
        self.Yaw_label.setScaledContents(False)
        self.Yaw_label.setObjectName("Yaw_label")
        self.Refresh_button = QtWidgets.QPushButton(self.tab)
        self.Refresh_button.setGeometry(QtCore.QRect(150, 390, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Refresh_button.setFont(font)
        self.Refresh_button.setObjectName("Refresh_button")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Logo_telkom = QtWidgets.QLabel(self.tab_2)
        self.Logo_telkom.setGeometry(QtCore.QRect(40, 40, 431, 421))
        font = QtGui.QFont()
        font.setFamily("Waree")
        self.Logo_telkom.setFont(font)
        self.Logo_telkom.setMouseTracking(False)
        self.Logo_telkom.setTabletTracking(False)
        self.Logo_telkom.setAcceptDrops(False)
        self.Logo_telkom.setAutoFillBackground(False)
        self.Logo_telkom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Logo_telkom.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Logo_telkom.setLineWidth(6)
        self.Logo_telkom.setMidLineWidth(12)
        self.Logo_telkom.setText("")
        self.Logo_telkom.setObjectName("Logo_telkom")
        self.Logo_robotic = QtWidgets.QLabel(self.tab_2)
        self.Logo_robotic.setGeometry(QtCore.QRect(530, 40, 431, 421))
        font = QtGui.QFont()
        font.setFamily("Waree")
        self.Logo_robotic.setFont(font)
        self.Logo_robotic.setMouseTracking(False)
        self.Logo_robotic.setTabletTracking(False)
        self.Logo_robotic.setAcceptDrops(False)
        self.Logo_robotic.setAutoFillBackground(False)
        self.Logo_robotic.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Logo_robotic.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Logo_robotic.setLineWidth(6)
        self.Logo_robotic.setMidLineWidth(12)
        self.Logo_robotic.setText("")
        self.Logo_robotic.setObjectName("Logo_robotic")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Start/Stop Button"))
        self.pushButton_Start.setText(_translate("Dialog", "Start"))
        self.pushButton_Stop.setText(_translate("Dialog", "Stop"))
        self.groupBox_3.setTitle(_translate("Dialog", "Sensor Value"))
        self.label_5.setText(_translate("Dialog", "Voltage (volt)"))
        self.label_6.setText(_translate("Dialog", "Temperature (*C)"))
        self.label_7.setText(_translate("Dialog", "Internal Presure"))
        self.label_8.setText(_translate("Dialog", "Current"))
        self.label_16.setText(_translate("Dialog", "Power (W)"))
        self.label_3.setText(_translate("Dialog", "TextLabel"))
        self.label_4.setText(_translate("Dialog", "TextLabel"))
        self.label_9.setText(_translate("Dialog", "TextLabel"))
        self.label_10.setText(_translate("Dialog", "TextLabel"))
        self.label_18.setText(_translate("Dialog", "Depth"))
        self.label_19.setText(_translate("Dialog", "TextLabel"))
        self.groupBox_6.setTitle(_translate("Dialog", "Robot Orientation"))
        self.label_21.setText(_translate("Dialog", "Roll"))
        self.label_22.setText(_translate("Dialog", "Pitch"))
        self.label_23.setText(_translate("Dialog", "Yaw"))
        self.label_24.setText(_translate("Dialog", "TextLabel"))
        self.label_25.setText(_translate("Dialog", "TextLabel"))
        self.label_26.setText(_translate("Dialog", "TextLabel"))
        self.groupBox_5.setTitle(_translate("Dialog", "Robot Orientation"))
        self.label_13.setText(_translate("Dialog", "Roll"))
        self.label_14.setText(_translate("Dialog", "Pitch"))
        self.label_15.setText(_translate("Dialog", "Yaw"))
        self.Refresh_button.setText(_translate("Dialog", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
