# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'krbai.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1048, 558)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1041, 531))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(380, 330, 231, 141))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_Start = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Start.setGeometry(QtCore.QRect(20, 70, 89, 25))
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.pushButton_Stop = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Stop.setGeometry(QtCore.QRect(120, 70, 89, 25))
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 471, 301))
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 161, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 131, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 130, 151, 61))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 190, 151, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lcdNumber_Voltage = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_Voltage.setGeometry(QtCore.QRect(190, 40, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(27)
        self.lcdNumber_Voltage.setFont(font)
        self.lcdNumber_Voltage.setAcceptDrops(False)
        self.lcdNumber_Voltage.setAutoFillBackground(True)
        self.lcdNumber_Voltage.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber_Voltage.setMidLineWidth(18)
        self.lcdNumber_Voltage.setSmallDecimalPoint(False)
        self.lcdNumber_Voltage.setDigitCount(11)
        self.lcdNumber_Voltage.setObjectName("lcdNumber_Voltage")
        self.lcdNumber_InternalPresure = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_InternalPresure.setGeometry(QtCore.QRect(190, 140, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(27)
        self.lcdNumber_InternalPresure.setFont(font)
        self.lcdNumber_InternalPresure.setAcceptDrops(False)
        self.lcdNumber_InternalPresure.setAutoFillBackground(True)
        self.lcdNumber_InternalPresure.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber_InternalPresure.setMidLineWidth(18)
        self.lcdNumber_InternalPresure.setSmallDecimalPoint(False)
        self.lcdNumber_InternalPresure.setDigitCount(11)
        self.lcdNumber_InternalPresure.setObjectName("lcdNumber_InternalPresure")
        self.lcdNumber_Temperature = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_Temperature.setGeometry(QtCore.QRect(190, 90, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(27)
        font.setUnderline(False)
        self.lcdNumber_Temperature.setFont(font)
        self.lcdNumber_Temperature.setAcceptDrops(False)
        self.lcdNumber_Temperature.setAutoFillBackground(True)
        self.lcdNumber_Temperature.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber_Temperature.setMidLineWidth(18)
        self.lcdNumber_Temperature.setSmallDecimalPoint(False)
        self.lcdNumber_Temperature.setDigitCount(11)
        self.lcdNumber_Temperature.setObjectName("lcdNumber_Temperature")
        self.lcdNumber_Depth = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_Depth.setGeometry(QtCore.QRect(190, 240, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(27)
        self.lcdNumber_Depth.setFont(font)
        self.lcdNumber_Depth.setAcceptDrops(False)
        self.lcdNumber_Depth.setAutoFillBackground(True)
        self.lcdNumber_Depth.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber_Depth.setMidLineWidth(18)
        self.lcdNumber_Depth.setSmallDecimalPoint(False)
        self.lcdNumber_Depth.setDigitCount(11)
        self.lcdNumber_Depth.setObjectName("lcdNumber_Depth")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(20, 240, 67, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lcdNumber_Current = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_Current.setGeometry(QtCore.QRect(190, 190, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(27)
        self.lcdNumber_Current.setFont(font)
        self.lcdNumber_Current.setAcceptDrops(False)
        self.lcdNumber_Current.setAutoFillBackground(True)
        self.lcdNumber_Current.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber_Current.setMidLineWidth(18)
        self.lcdNumber_Current.setSmallDecimalPoint(False)
        self.lcdNumber_Current.setDigitCount(11)
        self.lcdNumber_Current.setObjectName("lcdNumber_Current")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(510, 10, 471, 301))
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(20, 40, 151, 31))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(20, 130, 131, 41))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(20, 210, 151, 61))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lcdNumber_Roll = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_Roll.setGeometry(QtCore.QRect(170, 40, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(27)
        self.lcdNumber_Roll.setFont(font)
        self.lcdNumber_Roll.setAcceptDrops(False)
        self.lcdNumber_Roll.setAutoFillBackground(True)
        self.lcdNumber_Roll.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber_Roll.setMidLineWidth(18)
        self.lcdNumber_Roll.setSmallDecimalPoint(False)
        self.lcdNumber_Roll.setDigitCount(11)
        self.lcdNumber_Roll.setObjectName("lcdNumber_Roll")
        self.lcdNumber_Yaw = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_Yaw.setGeometry(QtCore.QRect(170, 220, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(27)
        self.lcdNumber_Yaw.setFont(font)
        self.lcdNumber_Yaw.setAcceptDrops(False)
        self.lcdNumber_Yaw.setAutoFillBackground(True)
        self.lcdNumber_Yaw.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber_Yaw.setMidLineWidth(18)
        self.lcdNumber_Yaw.setSmallDecimalPoint(False)
        self.lcdNumber_Yaw.setDigitCount(11)
        self.lcdNumber_Yaw.setObjectName("lcdNumber_Yaw")
        self.lcdNumber_Pitch = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_Pitch.setGeometry(QtCore.QRect(170, 130, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono CJK SC")
        font.setPointSize(27)
        font.setUnderline(False)
        self.lcdNumber_Pitch.setFont(font)
        self.lcdNumber_Pitch.setAcceptDrops(False)
        self.lcdNumber_Pitch.setAutoFillBackground(True)
        self.lcdNumber_Pitch.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber_Pitch.setMidLineWidth(18)
        self.lcdNumber_Pitch.setSmallDecimalPoint(False)
        self.lcdNumber_Pitch.setDigitCount(11)
        self.lcdNumber_Pitch.setObjectName("lcdNumber_Pitch")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(10, 10, 461, 201))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [UKWN]")
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 10, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Waree")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Sensor_label = QtWidgets.QLabel(self.frame)
        self.Sensor_label.setGeometry(QtCore.QRect(10, 30, 431, 161))
        font = QtGui.QFont()
        font.setFamily("Waree")
        self.Sensor_label.setFont(font)
        self.Sensor_label.setMouseTracking(False)
        self.Sensor_label.setTabletTracking(False)
        self.Sensor_label.setAcceptDrops(False)
        self.Sensor_label.setAutoFillBackground(True)
        self.Sensor_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Sensor_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Sensor_label.setLineWidth(6)
        self.Sensor_label.setMidLineWidth(12)
        self.Sensor_label.setText("")
        self.Sensor_label.setObjectName("Sensor_label")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Start/Stop Button"))
        self.pushButton_Start.setText(_translate("Dialog", "Start"))
        self.pushButton_Stop.setText(_translate("Dialog", "Stop"))
        self.groupBox_3.setTitle(_translate("Dialog", "Sensor Value"))
        self.label_5.setText(_translate("Dialog", "Voltage"))
        self.label_6.setText(_translate("Dialog", "Temperature"))
        self.label_7.setText(_translate("Dialog", "Internal Presure"))
        self.label_8.setText(_translate("Dialog", "Current"))
        self.label_16.setText(_translate("Dialog", "Depth"))
        self.groupBox_5.setTitle(_translate("Dialog", "Robot Orientation"))
        self.label_13.setText(_translate("Dialog", "Roll"))
        self.label_14.setText(_translate("Dialog", "Pitch"))
        self.label_15.setText(_translate("Dialog", "Yaw"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tab 1"))
        self.label.setText(_translate("Dialog", "Sensor Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
