# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sensor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 0, 421, 251))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 150, 31, 16))
        self.label.setObjectName("label")
        self.label_pitch = QtWidgets.QLabel(self.groupBox)
        self.label_pitch.setGeometry(QtCore.QRect(70, 40, 231, 41))
        self.label_pitch.setAutoFillBackground(True)
        self.label_pitch.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_pitch.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_pitch.setLineWidth(5)
        self.label_pitch.setMidLineWidth(19)
        self.label_pitch.setText("")
        self.label_pitch.setObjectName("label_pitch")
        self.label_roll = QtWidgets.QLabel(self.groupBox)
        self.label_roll.setGeometry(QtCore.QRect(70, 90, 231, 41))
        self.label_roll.setAutoFillBackground(True)
        self.label_roll.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_roll.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_roll.setLineWidth(5)
        self.label_roll.setMidLineWidth(19)
        self.label_roll.setText("")
        self.label_roll.setObjectName("label_roll")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 41, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 41, 17))
        self.label_5.setObjectName("label_5")
        self.label_yaw = QtWidgets.QLabel(self.groupBox)
        self.label_yaw.setGeometry(QtCore.QRect(70, 140, 231, 41))
        self.label_yaw.setAutoFillBackground(True)
        self.label_yaw.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_yaw.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_yaw.setLineWidth(5)
        self.label_yaw.setMidLineWidth(19)
        self.label_yaw.setText("")
        self.label_yaw.setObjectName("label_yaw")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 51, 16))
        self.label_7.setObjectName("label_7")
        self.label_depth = QtWidgets.QLabel(self.groupBox)
        self.label_depth.setGeometry(QtCore.QRect(70, 190, 231, 41))
        self.label_depth.setAutoFillBackground(True)
        self.label_depth.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_depth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_depth.setLineWidth(5)
        self.label_depth.setMidLineWidth(19)
        self.label_depth.setText("")
        self.label_depth.setObjectName("label_depth")
        self.frame_camera = QtWidgets.QFrame(self.centralwidget)
        self.frame_camera.setGeometry(QtCore.QRect(30, 260, 421, 281))
        self.frame_camera.setMouseTracking(False)
        self.frame_camera.setTabletTracking(False)
        self.frame_camera.setAutoFillBackground(True)
        self.frame_camera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_camera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_camera.setObjectName("frame_camera")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "SENSOR"))
        self.label.setText(_translate("MainWindow", "YAW"))
        self.label_4.setText(_translate("MainWindow", "PITCH"))
        self.label_5.setText(_translate("MainWindow", "ROLL"))
        self.label_7.setText(_translate("MainWindow", "DEPTH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
